### ISSUE TITLE
llm_grpo_nanov3_30BA3B_2n8g_megatron_pack_cp test failure after #2529

### ISSUE THREAD

**Issue by kajalj22** [NVIDIA-NeMo/RL#2611]
**Describe the bug**

Nightly test failing with this error: 

llm_grpo_nanov3_30BA3B_2n8g_megatron_pack_cp
ImportError: cannot import name 'GreedySearchDecoderOnlyOutput' from 'transformers.generation'

**Steps/Code to reproduce bug**

Reproduceable from main branch 
A helpful guide on on how to craft a minimal bug report http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports.

**Expected behavior**

**Additional context**

Failing after this PR: https://github.com/NVIDIA-NeMo/RL/pull/2529
